services:
  - type: web
    name: crew-ai-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    runtime:
      python_version: 3.10
